-- MySQL Script generated by MySQL Workbench
-- Sat Jun 23 12:30:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fapair2_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fapair2_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fapair2_2` DEFAULT CHARACTER SET latin1 ;
USE `fapair2_2` ;

-- -----------------------------------------------------
-- Table `fapair2_2`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fapair2_2`.`manufacturer` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fapair2_2`.`aircraftType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fapair2_2`.`aircraftType` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `manufacturer_ID` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `size` INT(11) NOT NULL,
  `isCargo/isPerson` VARCHAR(10) NOT NULL,
  `pricePerKm` INT(11) NOT NULL,
  `capacity/seating` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `manufacturer_ID2manufacturer` (`manufacturer_ID` ASC),
  CONSTRAINT `manufacturer_ID2manufacturer`
    FOREIGN KEY (`manufacturer_ID`)
    REFERENCES `fapair2_2`.`manufacturer` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fapair2_2`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fapair2_2`.`status` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fapair2_2`.`aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fapair2_2`.`aircraft` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `aircraftType_ID` INT(11) NOT NULL,
  `status_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `aircraftType_ID2aircraftType` (`aircraftType_ID` ASC),
  INDEX `status_ID2status` (`status_ID` ASC),
  CONSTRAINT `aircraftType_ID2aircraftType`
    FOREIGN KEY (`aircraftType_ID`)
    REFERENCES `fapair2_2`.`aircraftType` (`ID`),
  CONSTRAINT `status_ID2status`
    FOREIGN KEY (`status_ID`)
    REFERENCES `fapair2_2`.`status` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fapair2_2`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fapair2_2`.`country` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fapair2_2`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fapair2_2`.`airport` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `country_ID` INT(11) NOT NULL,
  `abbreviation` VARCHAR(10) NOT NULL,
  `airportName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `city_ID2city_idx` (`country_ID` ASC),
  CONSTRAINT `city_ID2city`
    FOREIGN KEY (`country_ID`)
    REFERENCES `fapair2_2`.`country` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fapair2_2`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fapair2_2`.`city` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `country_ID` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `country_ID2country` (`country_ID` ASC),
  CONSTRAINT `country_ID2country`
    FOREIGN KEY (`country_ID`)
    REFERENCES `fapair2_2`.`country` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fapair2_2`.`flightDestination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fapair2_2`.`flightDestination` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `startAirport` INT(11) NOT NULL,
  `destinationAirport` INT(11) NOT NULL,
  `distance` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `startAirport2airport` (`startAirport` ASC),
  INDEX `destinationAirport2airport` (`destinationAirport` ASC),
  CONSTRAINT `destinationAirport2airport`
    FOREIGN KEY (`destinationAirport`)
    REFERENCES `fapair2_2`.`airport` (`ID`),
  CONSTRAINT `startAirport2airport`
    FOREIGN KEY (`startAirport`)
    REFERENCES `fapair2_2`.`airport` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fapair2_2`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fapair2_2`.`flight` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `aircraft_ID` INT(11) NOT NULL,
  `flightDestination_ID` INT(11) NOT NULL,
  `costs` INT(11) NOT NULL,
  `incomings` INT(11) NOT NULL,
  `startingTime` DATETIME NOT NULL,
  `landingTime` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `aircraft_ID2aircraft` (`aircraft_ID` ASC),
  INDEX `flightDestination_ID2flightDestination` (`flightDestination_ID` ASC),
  CONSTRAINT `aircraft_ID2aircraft`
    FOREIGN KEY (`aircraft_ID`)
    REFERENCES `fapair2_2`.`aircraft` (`ID`),
  CONSTRAINT `flightDestination_ID2flightDestination`
    FOREIGN KEY (`flightDestination_ID`)
    REFERENCES `fapair2_2`.`flightDestination` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fapair2_2`.`gateName`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fapair2_2`.`gateName` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fapair2_2`.`gate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fapair2_2`.`gate` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `airport_ID` INT(11) NOT NULL,
  `gateName_ID` INT(11) NOT NULL,
  `available` VARCHAR(10) NOT NULL,
  `outside/inside` VARCHAR(20) NOT NULL,
  `sizeRequirement` INT(11) NOT NULL,
  `costsPerHour` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `gateName_ID2gateName` (`gateName_ID` ASC),
  INDEX `airport_ID2airport` (`airport_ID` ASC),
  CONSTRAINT `airport_ID2airport`
    FOREIGN KEY (`airport_ID`)
    REFERENCES `fapair2_2`.`airport` (`ID`),
  CONSTRAINT `gateName_ID2gateName`
    FOREIGN KEY (`gateName_ID`)
    REFERENCES `fapair2_2`.`gateName` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
