/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
//import methods.TableFromDatabase;
//import methods.TableFromDatabase;
import methods.*;

/**
 *
 * @author hfpma
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSideMenu = new javax.swing.JPanel();
        btn_Fleet = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ind_Fleet = new javax.swing.JPanel();
        btn_Routes = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ind_Routes = new javax.swing.JPanel();
        btn_Calculate = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        ind_Calculate = new javax.swing.JPanel();
        btn_Airports = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        ind_Airports = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabelMenu = new javax.swing.JLabel();
        jLabelMenuIcon = new javax.swing.JLabel();
        jLabelMenuIcon1 = new javax.swing.JLabel();
        jMainPanel = new javax.swing.JPanel();
        jPanelHome = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanelPlane = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelLocation = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jLabelTypeDef = new javax.swing.JLabel();
        jLabelStatusDef = new javax.swing.JLabel();
        jLabelLocationDef = new javax.swing.JLabel();
        jLabelSizeDef = new javax.swing.JLabel();
        jLabelSize = new javax.swing.JLabel();
        jLabelCapacaityDef = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelCapacity = new javax.swing.JLabel();
        jLabelPriceDef = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonEditPlane = new javax.swing.JButton();
        jLabelPlaneName3 = new javax.swing.JLabel();
        jPanelFlight = new javax.swing.JPanel();
        jLabelPlaneName1 = new javax.swing.JLabel();
        jLabelType1 = new javax.swing.JLabel();
        jLabelTypeDef1 = new javax.swing.JLabel();
        jLabelType2 = new javax.swing.JLabel();
        jLabelTypeDef2 = new javax.swing.JLabel();
        jLabelType3 = new javax.swing.JLabel();
        jLabelTypeDef3 = new javax.swing.JLabel();
        jLabelType4 = new javax.swing.JLabel();
        jLabelTypeDef4 = new javax.swing.JLabel();
        jLabelType5 = new javax.swing.JLabel();
        jLabelTypeDef5 = new javax.swing.JLabel();
        jLabelType6 = new javax.swing.JLabel();
        jLabelTypeDef6 = new javax.swing.JLabel();
        jLabelType7 = new javax.swing.JLabel();
        jLabelTypeDef7 = new javax.swing.JLabel();
        jLabelType8 = new javax.swing.JLabel();
        jLabelTypeDef8 = new javax.swing.JLabel();
        jLabelType9 = new javax.swing.JLabel();
        jLabelTypeDef9 = new javax.swing.JLabel();
        jLabelType10 = new javax.swing.JLabel();
        jLabelTypeDef10 = new javax.swing.JLabel();
        jLabelType11 = new javax.swing.JLabel();
        jLabelTypeDef11 = new javax.swing.JLabel();
        jLabelType12 = new javax.swing.JLabel();
        jLabelTypeDef12 = new javax.swing.JLabel();
        jButtonEditRoute = new javax.swing.JButton();
        jPanelFlights = new javax.swing.JPanel();
        jLabelPlaneName2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanelCalculateCost = new javax.swing.JPanel();
        jLabelCalculateCost = new javax.swing.JLabel();
        jLabelType13 = new javax.swing.JLabel();
        jLabelType14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabelType15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelType16 = new javax.swing.JLabel();
        jLabelType17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCommercial = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanelCargo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSideMenu.setBackground(new java.awt.Color(0, 204, 255));
        jSideMenu.setPreferredSize(new java.awt.Dimension(267, 486));

        btn_Fleet.setBackground(new java.awt.Color(0, 204, 255));
        btn_Fleet.setPreferredSize(new java.awt.Dimension(267, 40));
        btn_Fleet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_FleetMousePressed(evt);
            }
        });
        btn_Fleet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Fleet");
        btn_Fleet.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, -1, -1));

        ind_Fleet.setBackground(new java.awt.Color(0, 0, 255));
        ind_Fleet.setOpaque(false);
        ind_Fleet.setPreferredSize(new java.awt.Dimension(7, 40));

        javax.swing.GroupLayout ind_FleetLayout = new javax.swing.GroupLayout(ind_Fleet);
        ind_Fleet.setLayout(ind_FleetLayout);
        ind_FleetLayout.setHorizontalGroup(
            ind_FleetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ind_FleetLayout.setVerticalGroup(
            ind_FleetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_Fleet.add(ind_Fleet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 40));

        btn_Routes.setBackground(new java.awt.Color(0, 204, 255));
        btn_Routes.setPreferredSize(new java.awt.Dimension(267, 40));
        btn_Routes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_RoutesMousePressed(evt);
            }
        });
        btn_Routes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Routes");
        btn_Routes.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, -1, -1));

        ind_Routes.setBackground(new java.awt.Color(0, 0, 255));
        ind_Routes.setOpaque(false);
        ind_Routes.setPreferredSize(new java.awt.Dimension(7, 40));

        javax.swing.GroupLayout ind_RoutesLayout = new javax.swing.GroupLayout(ind_Routes);
        ind_Routes.setLayout(ind_RoutesLayout);
        ind_RoutesLayout.setHorizontalGroup(
            ind_RoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ind_RoutesLayout.setVerticalGroup(
            ind_RoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_Routes.add(ind_Routes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 40));

        btn_Calculate.setBackground(new java.awt.Color(0, 204, 255));
        btn_Calculate.setPreferredSize(new java.awt.Dimension(267, 40));
        btn_Calculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CalculateMousePressed(evt);
            }
        });
        btn_Calculate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Calculate ");
        btn_Calculate.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, -1, -1));

        ind_Calculate.setBackground(new java.awt.Color(0, 0, 255));
        ind_Calculate.setOpaque(false);
        ind_Calculate.setPreferredSize(new java.awt.Dimension(7, 40));

        javax.swing.GroupLayout ind_CalculateLayout = new javax.swing.GroupLayout(ind_Calculate);
        ind_Calculate.setLayout(ind_CalculateLayout);
        ind_CalculateLayout.setHorizontalGroup(
            ind_CalculateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ind_CalculateLayout.setVerticalGroup(
            ind_CalculateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_Calculate.add(ind_Calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 40));

        btn_Airports.setBackground(new java.awt.Color(0, 204, 255));
        btn_Airports.setPreferredSize(new java.awt.Dimension(267, 40));
        btn_Airports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_AirportsMousePressed(evt);
            }
        });
        btn_Airports.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Airports");
        btn_Airports.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, -1, -1));

        ind_Airports.setBackground(new java.awt.Color(0, 0, 255));
        ind_Airports.setOpaque(false);
        ind_Airports.setPreferredSize(new java.awt.Dimension(7, 40));

        javax.swing.GroupLayout ind_AirportsLayout = new javax.swing.GroupLayout(ind_Airports);
        ind_Airports.setLayout(ind_AirportsLayout);
        ind_AirportsLayout.setHorizontalGroup(
            ind_AirportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ind_AirportsLayout.setVerticalGroup(
            ind_AirportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_Airports.add(ind_Airports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 40));

        jPanel9.setBackground(new java.awt.Color(0, 204, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(267, 40));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("#####");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, -1, -1));

        jPanel10.setBackground(new java.awt.Color(0, 0, 255));
        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(7, 40));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 40));

        jLabelMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMenu.setText(" Menu");

        jLabelMenuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu-512.png"))); // NOI18N
        jLabelMenuIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMenuIconMousePressed(evt);
            }
        });

        jLabelMenuIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu-512.png"))); // NOI18N
        jLabelMenuIcon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMenuIcon1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jSideMenuLayout = new javax.swing.GroupLayout(jSideMenu);
        jSideMenu.setLayout(jSideMenuLayout);
        jSideMenuLayout.setHorizontalGroup(
            jSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Fleet, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btn_Routes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btn_Calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jSideMenuLayout.createSequentialGroup()
                .addGroup(jSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Airports, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSideMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMenuIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMenuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jSideMenuLayout.setVerticalGroup(
            jSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSideMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMenuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMenuIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_Fleet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Routes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Calculate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Airports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        jMainPanel.setLayout(new java.awt.CardLayout());

        jPanelHome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/paper-plane.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel16.setText("FAP-AIR v1.3");

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(257, 257, 257))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel15)
                .addGap(44, 44, 44)
                .addComponent(jLabel16)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jMainPanel.add(jPanelHome, "card7");

        jPanelPlane.setBackground(new java.awt.Color(255, 255, 255));

        jLabelStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelStatus.setText("Status");

        jLabelLocation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelLocation.setText("Location");

        jLabelType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType.setText("Type");

        jLabelTypeDef.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTypeDef.setText("TypeDef");

        jLabelStatusDef.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelStatusDef.setText("StatusDef");

        jLabelLocationDef.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLocationDef.setText("LocationDef");

        jLabelSizeDef.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSizeDef.setText("SizeDef");

        jLabelSize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSize.setText("Size");

        jLabelCapacaityDef.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCapacaityDef.setText("CapacatiyDef");

        jLabelPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPrice.setText("Price/km");

        jLabelCapacity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCapacity.setText("Capacatiy");

        jLabelPriceDef.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPriceDef.setText("PriceDef");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonEditPlane.setText("Edit Plane");

        jLabelPlaneName3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelPlaneName3.setText("Plane_Name");

        javax.swing.GroupLayout jPanelPlaneLayout = new javax.swing.GroupLayout(jPanelPlane);
        jPanelPlane.setLayout(jPanelPlaneLayout);
        jPanelPlaneLayout.setHorizontalGroup(
            jPanelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlaneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTypeDef)
                    .addGroup(jPanelPlaneLayout.createSequentialGroup()
                        .addGroup(jPanelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStatusDef)
                            .addComponent(jLabelType)
                            .addComponent(jLabelStatus)
                            .addComponent(jLabelLocation)
                            .addComponent(jLabelLocationDef))
                        .addGap(116, 116, 116)
                        .addGroup(jPanelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrice)
                            .addComponent(jLabelCapacaityDef)
                            .addComponent(jLabelSize)
                            .addComponent(jLabelSizeDef)
                            .addComponent(jLabelCapacity)
                            .addComponent(jLabelPriceDef))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditPlane)
                .addContainerGap())
            .addGroup(jPanelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPlaneLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabelPlaneName3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(465, Short.MAX_VALUE)))
        );
        jPanelPlaneLayout.setVerticalGroup(
            jPanelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlaneLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType)
                    .addComponent(jLabelSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTypeDef)
                    .addComponent(jLabelSizeDef))
                .addGap(18, 18, 18)
                .addGroup(jPanelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jLabelCapacity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatusDef)
                    .addComponent(jLabelCapacaityDef))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocationDef)
                    .addComponent(jLabelPriceDef))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditPlane)
                .addGap(81, 81, 81))
            .addGroup(jPanelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPlaneLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabelPlaneName3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(556, Short.MAX_VALUE)))
        );

        jMainPanel.add(jPanelPlane, "card2");

        jPanelFlight.setBackground(new java.awt.Color(255, 255, 255));

        jLabelPlaneName1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelPlaneName1.setText("Flight_From_To_ID");

        jLabelType1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType1.setText("Plane");

        jLabelTypeDef1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTypeDef1.setText("PlaneDef");

        jLabelType2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType2.setText("Type");

        jLabelTypeDef2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTypeDef2.setText("TypeDef");

        jLabelType3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType3.setText("Departure Time");

        jLabelTypeDef3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTypeDef3.setText("DepartureTime");

        jLabelType4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType4.setText("Arrival Time");

        jLabelTypeDef4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTypeDef4.setText("ArrivalTime");

        jLabelType5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType5.setText("Flight Time");

        jLabelTypeDef5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTypeDef5.setText("Dep-ArrTime");

        jLabelType6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType6.setText("Distance");

        jLabelTypeDef6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTypeDef6.setText("Distance in Km");

        jLabelType7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType7.setText("Frequency");

        jLabelTypeDef7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTypeDef7.setText("daily,weekly etc");

        jLabelType8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType8.setText("Calculated Cost");

        jLabelTypeDef8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTypeDef8.setText("Cost");

        jLabelType9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType9.setText("Rec. Ticket Price");

        jLabelTypeDef9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTypeDef9.setText("recommendPrice");

        jLabelType10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType10.setText("Actual Price");

        jLabelTypeDef10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTypeDef10.setText("actualPrice");

        jLabelType11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType11.setText("efficency");

        jLabelTypeDef11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTypeDef11.setText("actualPrice/recommended");

        jLabelType12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType12.setText("Remarks/Comments");

        jLabelTypeDef12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTypeDef12.setText("remarks");

        jButtonEditRoute.setText("Edit Route");
        jButtonEditRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditRouteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFlightLayout = new javax.swing.GroupLayout(jPanelFlight);
        jPanelFlight.setLayout(jPanelFlightLayout);
        jPanelFlightLayout.setHorizontalGroup(
            jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTypeDef6)
                            .addComponent(jLabelType6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTypeDef1)
                            .addComponent(jLabelType1)
                            .addComponent(jLabelTypeDef3)
                            .addComponent(jLabelType3)
                            .addComponent(jLabelTypeDef8)
                            .addComponent(jLabelType8))
                        .addGap(75, 75, 75)
                        .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelFlightLayout.createSequentialGroup()
                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTypeDef2)
                                    .addComponent(jLabelType2)
                                    .addComponent(jLabelTypeDef7)
                                    .addComponent(jLabelType7))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFlightLayout.createSequentialGroup()
                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTypeDef4)
                                    .addComponent(jLabelType4)
                                    .addComponent(jLabelTypeDef9)
                                    .addComponent(jLabelType9))
                                .addGap(105, 105, 105)
                                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTypeDef5)
                                    .addComponent(jLabelType5)
                                    .addComponent(jLabelTypeDef10)
                                    .addComponent(jLabelType10))
                                .addContainerGap(59, Short.MAX_VALUE))))
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPlaneName1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTypeDef11)
                            .addComponent(jLabelType11)
                            .addComponent(jLabelTypeDef12)
                            .addComponent(jLabelType12))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFlightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditRoute)
                .addContainerGap())
        );
        jPanelFlightLayout.setVerticalGroup(
            jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPlaneName1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addComponent(jLabelType1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTypeDef1))
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addComponent(jLabelType2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTypeDef2)))
                .addGap(18, 18, 18)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addComponent(jLabelType3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTypeDef3))
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addComponent(jLabelType4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTypeDef4))
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addComponent(jLabelType5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTypeDef5)))
                .addGap(18, 18, 18)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addComponent(jLabelType6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTypeDef6))
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addComponent(jLabelType7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTypeDef7)))
                .addGap(18, 18, 18)
                .addGroup(jPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addComponent(jLabelType8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTypeDef8))
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addComponent(jLabelType9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTypeDef9))
                    .addGroup(jPanelFlightLayout.createSequentialGroup()
                        .addComponent(jLabelType10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTypeDef10)))
                .addGap(18, 18, 18)
                .addComponent(jLabelType11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTypeDef11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelType12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTypeDef12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButtonEditRoute)
                .addContainerGap())
        );

        jMainPanel.add(jPanelFlight, "card3");

        jPanelFlights.setBackground(new java.awt.Color(255, 255, 255));

        jLabelPlaneName2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelPlaneName2.setText("Flights");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Add flight");

        javax.swing.GroupLayout jPanelFlightsLayout = new javax.swing.GroupLayout(jPanelFlights);
        jPanelFlights.setLayout(jPanelFlightsLayout);
        jPanelFlightsLayout.setHorizontalGroup(
            jPanelFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFlightsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPlaneName2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFlightsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanelFlightsLayout.setVerticalGroup(
            jPanelFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFlightsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPlaneName2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jMainPanel.add(jPanelFlights, "card4");

        jPanelCalculateCost.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCalculateCost.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelCalculateCost.setText("Calculate Cost");

        jLabelType13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType13.setText("Plane");

        jLabelType14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType14.setText("Flight");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Type");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("averrange Passengers:");

        jLabelType15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType15.setText("Costs");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Landing:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Starting:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Fuel:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Demurrage:");

        jLabelType16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType16.setText("Calculate Costs:");

        jLabelType17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelType17.setText("Ticket Price for break even:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Flight route");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("price");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("cost");

        jLabel17.setText(null);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Flight route");

        javax.swing.GroupLayout jPanelCalculateCostLayout = new javax.swing.GroupLayout(jPanelCalculateCost);
        jPanelCalculateCost.setLayout(jPanelCalculateCostLayout);
        jPanelCalculateCostLayout.setHorizontalGroup(
            jPanelCalculateCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalculateCostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCalculateCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCalculateCostLayout.createSequentialGroup()
                        .addGroup(jPanelCalculateCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelType13)
                            .addComponent(jLabelType14)
                            .addComponent(jLabelType15)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCalculateCost, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCalculateCostLayout.createSequentialGroup()
                                .addGroup(jPanelCalculateCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelType16)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanelCalculateCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelType17))))
                        .addContainerGap(174, Short.MAX_VALUE))
                    .addGroup(jPanelCalculateCostLayout.createSequentialGroup()
                        .addGroup(jPanelCalculateCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCalculateCostLayout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addGroup(jPanelCalculateCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanelCalculateCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCalculateCostLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCalculateCostLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))))
        );
        jPanelCalculateCostLayout.setVerticalGroup(
            jPanelCalculateCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalculateCostLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCalculateCost, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelType13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCalculateCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(jLabelType14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCalculateCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jLabelType15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanelCalculateCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType16)
                    .addComponent(jLabelType17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCalculateCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jMainPanel.add(jPanelCalculateCost, "card5");

        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable3MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanelCommercialLayout = new javax.swing.GroupLayout(jPanelCommercial);
        jPanelCommercial.setLayout(jPanelCommercialLayout);
        jPanelCommercialLayout.setHorizontalGroup(
            jPanelCommercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jPanelCommercialLayout.setVerticalGroup(
            jPanelCommercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("commercial aircraft", jPanelCommercial);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanelCargoLayout = new javax.swing.GroupLayout(jPanelCargo);
        jPanelCargo.setLayout(jPanelCargoLayout);
        jPanelCargoLayout.setHorizontalGroup(
            jPanelCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jPanelCargoLayout.setVerticalGroup(
            jPanelCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("cargo aircraft", jPanelCargo);

        jMainPanel.add(jTabbedPane1, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
            .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditRouteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditRouteActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btn_FleetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FleetMousePressed
        // TODO add your handling code here:

        jMainPanel.removeAll();
        jMainPanel.repaint();
        jMainPanel.revalidate();
        jMainPanel.add(jTabbedPane1);
        jMainPanel.repaint();
        jMainPanel.revalidate();

        setColor(btn_Fleet);
        resetColor(btn_Airports);
        resetColor(btn_Calculate);
        resetColor(btn_Routes);
        ind_Fleet.setOpaque(true);
        ind_Airports.setOpaque(false);
        ind_Calculate.setOpaque(false);
        ind_Routes.setOpaque(false);

    }//GEN-LAST:event_btn_FleetMousePressed

    private void btn_RoutesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RoutesMousePressed
        // TODO add your handling code here:

        jMainPanel.removeAll();
        jMainPanel.repaint();
        jMainPanel.revalidate();
        jMainPanel.add(jPanelFlights);
        jMainPanel.repaint();
        jMainPanel.revalidate();

        setColor(btn_Routes);
        resetColor(btn_Airports);
        resetColor(btn_Calculate);
        resetColor(btn_Fleet);
        ind_Fleet.setOpaque(false);
        ind_Airports.setOpaque(false);
        ind_Calculate.setOpaque(false);
        ind_Routes.setOpaque(true);
    }//GEN-LAST:event_btn_RoutesMousePressed


    private void btn_CalculateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CalculateMousePressed
        // TODO add your handling code here:

        jMainPanel.removeAll();
        jMainPanel.repaint();
        jMainPanel.revalidate();
        jMainPanel.add(jPanelCalculateCost);
        jMainPanel.repaint();
        jMainPanel.revalidate();

        setColor(btn_Calculate);
        resetColor(btn_Airports);
        resetColor(btn_Routes);
        resetColor(btn_Fleet);
        ind_Fleet.setOpaque(false);
        ind_Airports.setOpaque(false);
        ind_Calculate.setOpaque(true);
        ind_Routes.setOpaque(false);

    }//GEN-LAST:event_btn_CalculateMousePressed

    private void btn_AirportsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AirportsMousePressed
        // TODO add your handling code here:

        setColor(btn_Airports);
        resetColor(btn_Calculate);
        resetColor(btn_Routes);
        resetColor(btn_Fleet);
        ind_Fleet.setOpaque(false);
        ind_Airports.setOpaque(true);
        ind_Calculate.setOpaque(false);
        ind_Routes.setOpaque(false);
    }//GEN-LAST:event_btn_AirportsMousePressed

    private void jLabelMenuIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuIconMousePressed
        // TODO add your handling code here:

        Thread th = new Thread() {
            @Override
            public void run() {
                int x = 180;
                int y = 26;
                try {
                    for (int a = 0; a <= 5; a++) {
                        Thread.sleep(50);
                        jSideMenu.setSize(x, 618);
                        jMainPanel.setBounds(x + 5, 0, 655 + y, 618);
                        jLabelMenuIcon.setBounds(x - 45, 6, 35, 39);
                        x -= 26;
                        y += y;

                        if (a == 5) {
                            jLabelMenuIcon1.setBounds(5, 6, 35, 39);
                        }

                        if (a == 5) {
                            jLabelMenuIcon.setSize(0, 0);
                        }

                    }
                    //if(x==130){

                    // jLabelMenuIcon.setVisible(false);}
                } catch (Exception ex) {
                    System.out.println(ex);
                }
            }
        };
        th.start();


    }//GEN-LAST:event_jLabelMenuIconMousePressed

    private void jLabelMenuIcon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuIcon1MousePressed
        // TODO add your handling code here:

        Thread th = new Thread() {
            @Override
            public void run() {
                int x = 50;
                int y = 26;
                try {
                    for (int a = 0; a <= 5; a++) {
                        Thread.sleep(50);
                        jSideMenu.setSize(x, 618);
                        jMainPanel.setBounds(x + 5, 0, 655, 618);
                        jLabelMenuIcon1.setBounds(x - 45, 6, 35, 39);
                        x += 26;
                        y += y;

                        if (a == 5) {
                            jLabelMenuIcon.setBounds(140, 6, 35, 39);

                            jLabelMenuIcon1.setSize(0, 0);

                        }
                    }
                    //if(x==130){

                    // jLabelMenuIcon.setVisible(false);}
                } catch (Exception ex) {
                    System.out.println(ex);
                }
            }
        };
        th.start();
    }//GEN-LAST:event_jLabelMenuIcon1MousePressed

    private void jTable3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MousePressed
        int index = jTable3.getSelectedRow();
        
        TableModel model = jTable3.getModel();
//        jMainPanel.removeAll();
//        jMainPanel.repaint();
//        jMainPanel.revalidate();
//        jMainPanel.add(jPanelPlane);
//        jMainPanel.repaint();
//        jMainPanel.revalidate();
        changePane.change(jMainPanel, jPanelPlane);
        
        String id = model.getValueAt(index, 0).toString();
        String firstName = model.getValueAt(index, 1).toString();
        String lastName = model.getValueAt(index, 2).toString();
        String age = model.getValueAt(index, 3).toString();
          System.out.println(firstName);
        
        jLabelTypeDef.setText(id);
        jLabelStatusDef.setText(firstName);
        jLabelLocationDef.setText(lastName);
        jLabelSizeDef.setText(age);
            }//GEN-LAST:event_jTable3MousePressed

    void setColor(JPanel panel) {
        panel.setBackground(new Color(0, 153, 255));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(0, 204, 255));
    }

    public static TableModel TableFromDatabasePerson() {

        Vector<Object> columnNames = new Vector<Object>();
        Vector<Object> data = new Vector<Object>();

        try {
            //  Connect to an Access Database

            connect c2db = new connect();
            Connection conn = c2db.conStart();

            //  Read data from a table
            String sql = "SELECT * FROM aircrafttype WHERE isCargoOrIsPerson Like '%Person%'";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            ResultSetMetaData md = rs.getMetaData();
            int columns = md.getColumnCount();

            //  Get column names
            for (int i = 1; i <= columns; i++) {
                columnNames.addElement(md.getColumnName(i));
            }

            //  Get row data
            while (rs.next()) {
                Vector<Object> row = new Vector<Object>(columns);

                for (int i = 1; i <= columns; i++) {
                    row.addElement(rs.getObject(i));
                }

                data.addElement(row);
            }

            rs.close();
            stmt.close();
            //conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        //  Create table with database data
        DefaultTableModel model = new DefaultTableModel(data, columnNames) {
            @Override
            public Class getColumnClass(int column) {
                for (int row = 0; row < getRowCount(); row++) {
                    Object o = getValueAt(row, column);

                    if (o != null) {
                        return o.getClass();
                    }
                }

                return Object.class;
            }
        };
        return model;

    }

    public static TableModel TableFromDatabaseCargo() {

        Vector<Object> columnNames = new Vector<Object>();
        Vector<Object> data = new Vector<Object>();

        try {
            //  Connect to an Access Database

            connect c2db = new connect();
            Connection conn = c2db.conStart();

            //  Read data from a table
            String sql = "SELECT * FROM aircrafttype WHERE isCargoOrIsPerson Like '%Cargo%'";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            ResultSetMetaData md = rs.getMetaData();
            int columns = md.getColumnCount();

            //  Get column names
            for (int i = 1; i <= columns; i++) {
                columnNames.addElement(md.getColumnName(i));
            }

            //  Get row data
            while (rs.next()) {
                Vector<Object> row = new Vector<Object>(columns);

                for (int i = 1; i <= columns; i++) {
                    row.addElement(rs.getObject(i));
                }

                data.addElement(row);
            }

            rs.close();
            stmt.close();
            //conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        //  Create table with database data
        DefaultTableModel model = new DefaultTableModel(data, columnNames) {
            @Override
            public Class getColumnClass(int column) {
                for (int row = 0; row < getRowCount(); row++) {
                    Object o = getValueAt(row, column);

                    if (o != null) {
                        return o.getClass();
                    }
                }

                return Object.class;
            }
        };
        return model;

    }

    public static TableModel TableFromDatabaseRoutes() {

        Vector<Object> columnNames = new Vector<Object>();
        Vector<Object> data = new Vector<Object>();

        try {
            //  Connect to an Access Database

            connect c2db = new connect();
            Connection conn = c2db.conStart();

            //  Read data from a table
            String sql = "SELECT * FROM flight";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            ResultSetMetaData md = rs.getMetaData();
            int columns = md.getColumnCount();

            //  Get column names
            for (int i = 1; i <= columns; i++) {
                columnNames.addElement(md.getColumnName(i));
            }

            //  Get row data
            while (rs.next()) {
                Vector<Object> row = new Vector<Object>(columns);

                for (int i = 1; i <= columns; i++) {
                    row.addElement(rs.getObject(i));
                }

                data.addElement(row);
            }

            rs.close();
            stmt.close();
            //conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        //  Create table with database data
        DefaultTableModel model = new DefaultTableModel(data, columnNames) {
            @Override
            public Class getColumnClass(int column) {
                for (int row = 0; row < getRowCount(); row++) {
                    Object o = getValueAt(row, column);

                    if (o != null) {
                        return o.getClass();
                    }
                }

                return Object.class;
            }
        };
        return model;

    }

        
                                       

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String command = "";
                int x;
                new MainWindow().setVisible(true);
                connect c2db = new connect();
                Connection conn = c2db.conStart();
                // ArrayList<String> str = new ArrayList<>();
                //str = c2db.ReadOutDB("SELECT ID FROM aircraft");
                //String[] index = str.toArray(new String[str.size()]);

                jTable3.setModel(TableFromDatabasePerson());
                jTable4.setModel(TableFromDatabaseCargo());
                jTable2.setModel(TableFromDatabaseRoutes());

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(c2db.ReadOutDB("SELECT ID FROM aircraft")));

                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(c2db.ReadOutDB("SELECT ID FROM flightdestination")));

                jComboBox1.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        //c2db.ReadOutDB("SELECT name FROM aircrafttype where ID like 1");
                        //jComboBox1.getSelectedItem().toString()
                        String help = jComboBox1.getSelectedItem().toString();
                        System.out.println(help);
                        //String help=c2db.ReadOutDB("SELECT destinationAirport FROM flightdestination inner join airport on airport.ID="+jComboBox2.getSelectedItem().toString())[0];

                        help = c2db.ReadOutString("SELECT aircraft.ID, name.aircraftType FROM aircraftType inner join aircraft on aircraftType.ID=aircraftType_ID");
                        jLabel17.setText(help);
                        System.out.println(help);
                        // now add back relevant values

                    }
                });

//                 jComboBox2.addActionListener(new ActionListener() {
//                    public void actionPerformed(ActionEvent e) {
//                        //c2db.ReadOutDB("SELECT name FROM aircrafttype where ID like 1");
//                        //jComboBox1.getSelectedItem().toString()
//                        String help=c2db.ReadOutDB("SELECT destinationAirport FROM flightdestination inner join airport on airport.ID="+jComboBox2.getSelectedItem().toString())[0];
//                        //String help2=c2db.ReadOutDB("SELECT airportname FROM airport inner join flightdestination on destinationAirport="+jComboBox2.getSelectedItem().toString())[0];
//                          // help=help+"-"+help2;
//                           System.out.println(help);
//                        jLabel7.setText(help);
//                        //System.out.println(help);
//                        // now add back relevant values
//
//                    }
//                });
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_Airports;
    private javax.swing.JPanel btn_Calculate;
    private javax.swing.JPanel btn_Fleet;
    private javax.swing.JPanel btn_Routes;
    private javax.swing.JPanel ind_Airports;
    private javax.swing.JPanel ind_Calculate;
    private javax.swing.JPanel ind_Fleet;
    private javax.swing.JPanel ind_Routes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEditPlane;
    private javax.swing.JButton jButtonEditRoute;
    public static javax.swing.JComboBox<String> jComboBox1;
    private static javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    private static javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private static javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCalculateCost;
    private javax.swing.JLabel jLabelCapacaityDef;
    private javax.swing.JLabel jLabelCapacity;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelLocationDef;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelMenuIcon;
    private javax.swing.JLabel jLabelMenuIcon1;
    private javax.swing.JLabel jLabelPlaneName1;
    private javax.swing.JLabel jLabelPlaneName2;
    private javax.swing.JLabel jLabelPlaneName3;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelPriceDef;
    private javax.swing.JLabel jLabelSize;
    private javax.swing.JLabel jLabelSizeDef;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStatusDef;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelType1;
    private javax.swing.JLabel jLabelType10;
    private javax.swing.JLabel jLabelType11;
    private javax.swing.JLabel jLabelType12;
    private javax.swing.JLabel jLabelType13;
    private javax.swing.JLabel jLabelType14;
    private javax.swing.JLabel jLabelType15;
    private javax.swing.JLabel jLabelType16;
    private javax.swing.JLabel jLabelType17;
    private javax.swing.JLabel jLabelType2;
    private javax.swing.JLabel jLabelType3;
    private javax.swing.JLabel jLabelType4;
    private javax.swing.JLabel jLabelType5;
    private javax.swing.JLabel jLabelType6;
    private javax.swing.JLabel jLabelType7;
    private javax.swing.JLabel jLabelType8;
    private javax.swing.JLabel jLabelType9;
    private javax.swing.JLabel jLabelTypeDef;
    private javax.swing.JLabel jLabelTypeDef1;
    private javax.swing.JLabel jLabelTypeDef10;
    private javax.swing.JLabel jLabelTypeDef11;
    private javax.swing.JLabel jLabelTypeDef12;
    private javax.swing.JLabel jLabelTypeDef2;
    private javax.swing.JLabel jLabelTypeDef3;
    private javax.swing.JLabel jLabelTypeDef4;
    private javax.swing.JLabel jLabelTypeDef5;
    private javax.swing.JLabel jLabelTypeDef6;
    private javax.swing.JLabel jLabelTypeDef7;
    private javax.swing.JLabel jLabelTypeDef8;
    private javax.swing.JLabel jLabelTypeDef9;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelCalculateCost;
    private javax.swing.JPanel jPanelCargo;
    private javax.swing.JPanel jPanelCommercial;
    private javax.swing.JPanel jPanelFlight;
    private javax.swing.JPanel jPanelFlights;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelPlane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jSideMenu;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private static javax.swing.JTable jTable2;
    private static javax.swing.JTable jTable3;
    private static javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
